services:
  akshare:  # AKShare 服务, 使用 AKTools 提供 HTTP API
    image: aktools:latest  # 注意：使用本地代码构建的 AKTools 镜像
    container_name: akshare_service
    ports:
      - "8080:8080"
    volumes:
      - ./akshare_data:/home  # 挂载数据目录（Windows路径需转换）
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    command: python -m aktools --host 0.0.0.0 --port 8080  # 添加启动命令

  stockinfo-analysis:
    build: ./stockinfo-analysis
    container_name: stockinfo_analysis_service
    ports:
      - "18080:18080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - rocketmq
    networks:
      - stockinfo-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: starter
      POSTGRES_PASSWORD: starter123
    ports:
      - "5432:5432"
    networks:
      - stockinfo-network

  rocketmq:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m -Xmn256m
    command: sh mqnamesrv
    networks:
      - stockinfo-network

  rocketmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-broker
    depends_on:
      - rocketmq
    ports:
      - "10911:10911"
      - "10909:10909"
    environment:
      - NAMESRV_ADDR=rocketmq:9876
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m -Xmn256m
    command: sh mqbroker -n rocketmq:9876 --enable-proxy
    networks:
      - stockinfo-network

networks:
  stockinfo-network:
    driver: bridge 

